blog/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
                  path('create/', BlogCreateView.as_view(), name='create'),
                  path('', BlogListView.as_view(), name='list'),
                  path('view/<int:pk>', BlogDetailView.as_view(), name='view'),
                  path('edit/<int:pk>', BlogUpdateView.as_view(), name='edit'),
                  path('delete/<int:pk>', BlogDeleteView.as_view(), name='delete'),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

djangoProject1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from blog.views import BlogListView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('', BlogListView.as_view(), name='list'),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models


class Blog(models.Model):
    title = models.CharField(max_length=150, verbose_name='название')
    slug = models.CharField(max_length=150, verbose_name='slug', null=True, blank=True)
    content = models.TextField(max_length=1000, verbose_name='содержание')
    preview = models.ImageField(verbose_name='изображение')
    date_of_creation = models.CharField(verbose_name='дата создания')
    is_published = models.BooleanField(default=True, verbose_name='опубликовано')
    views_count = models.IntegerField(default=0, verbose_name='просмотры')

    def __str__(self):
        return self.title


class Meta:
    verbose_name = 'статья'
    verbose_name_plural = 'статьи'

blog/views.py
from django.shortcuts import render
from django.urls import reverse_lazy, reverse

from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from pytils.translit import slugify

from blog.models import Blog


# Create your views here.
class BlogCreateView(CreateView):
    model = Blog
    fields = ('title', 'content', 'date_of_creation')
    success_url = reverse_lazy('blog:list')
    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()
        return super().form_valid(form)

class BlogListView(ListView):
    model = Blog
    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True)
        return queryset



class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object


class BlogUpdateView(UpdateView):
    model = Blog
    fields = ('title', 'slug', 'content', 'date_of_creation')
    #success_url = reverse_lazy('blog:list')
    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()
        return super().form_valid(form)
    def get_success_url(self):
        return reverse('blog:view', args=[self.kwargs.get('pk')])

class BlogDeleteView(DeleteView):
    model = Blog
    success_url = reverse_lazy('blog:list')

blog/templates/blog/blog_confirm_delete.html
{% extends 'catalog/base.html' %}
{% block content %}
    <div class = "row">
    <div class = "col-6">
        <div class = "card">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}

                    <p>Хотите удалить?"{{ object.title }}"</p>
                    <button type="submit" class="btn btn-success" >Подтвердить
                        <a href="{% url 'blog:list' %}"class="btn btn-warning">Отмена</a>
                    </button>
                </form>
            </div>
        </div>
    </div>
    </div>
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'catalog/base.html' %}
{% block content %}
       <div class="col-12">
       <div class="row">
           <div class="col-6">
       <div class="card">
       <div class="card-header">
               <h3 class="card-title">
                   Блог "{{ object.title }}" ({{ object.slug }})</h3>
                <div class="card-body">
                    <p>
                        {{ object.body }}
                    </p>
                    <div class="card-footer">
                        Просмотры: {{ object.views_count }}
                    </div>
  </div>
</div>
           </div>
               </div>
           </div>
       </div>

{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'catalog/base.html' %}
{% block content %}
    <div class="col-12"></div>
    <div class = "row">
    <div class = "col-6">
        <div class = "card">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                     <button type="submit" class="btn btn-success">
                    {% if object %}
                        Сохранить
                        {% else %}
                        Создать
                        {% endif %}
                    </button>
                </form>
            </div>
        </div>
    </div>
    </div>
    </div>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'catalog/base.html' %}
{% block content %}
    <div class="col-12 mb-5">
        <a class="btn-outline-primary" href="{% url 'blog:create' %}">Добавить блог</a>
    </div>
        {% for object in object_list %}
       <div class="card mb-4 box-shadow">
           <div class="card-body">
               <p class="card-text">
                   {{object|title}}
               </p>
               <div class="d-flex justify-content-between align-items-center">
                   <div class="btn-group">
                       <a href="{% url 'blog:view' object.pk %}"
                       class="btn btn-sm btn-outline-secondary">View</a>
                       <a href="{% url 'blog:edit' object.pk %}"
                       class="btn btn-sm btn-outline-secondary">Edit</a>
                       <a href="{% url 'blog:delete' object.pk %}"
                       class="btn btn-sm btn-outline-secondary">Delete</a>
               </div>
               </div>
  </div>
</div>
        {% endfor %}
{% endblock %}

blog/templates/blog/material_confirm_delete.html
{% extends 'catalog/base.html' %}
{% block content %}
    <div class = "row">
    <div class = "col-6">
        <div class = "card">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}

                    <p>Хотите удалить?"{{ object.title }}"</p>
                    <button type="submit" class="btn btn-success" >Подтвердить
                        <a href="{% url 'blog:list' %}"class="btn btn-warning">Отмена</a>
                    </button>
                </form>
            </div>
        </div>
    </div>
    </div>
{% endblock %}