blog/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
                  path('create/', BlogCreateView.as_view(), name='create'),
                  path('', BlogListView.as_view(), name='list'),
                  path('view/<int:pk>', BlogDetailView.as_view(), name='view'),
                  path('edit/<int:pk>', BlogUpdateView.as_view(), name='edit'),
                  path('delete/<int:pk>', BlogDeleteView.as_view(), name='delete'),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

catalog/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from blog.views import BlogListView, BlogCreateView, BlogDetailView, BlogUpdateView, BlogDeleteView
from catalog.views import contacts, ProductListView, ProductDetailView, ProductCreateView, ProductUpdateView, \
    VersionCreateView, VersionUpdateView, ProductDeleteView

app_name = 'catalog'

urlpatterns = [
    path('create/', ProductCreateView.as_view(), name='create_product'),
    path('update/<int:pk>', ProductUpdateView.as_view(), name='update_product'),
    path('delete/<int:pk>', ProductDeleteView.as_view(), name='delete_product'),
    path('', ProductListView.as_view(), name='home'),
    path('contacts/', contacts, name='contacts'),
    path('view/<int:pk>', ProductDetailView.as_view(), name='goods'),
    path('blog/', BlogListView.as_view(), name='list'),
    path('create/', BlogCreateView.as_view(), name='create'),
    path('view/<int:pk>', BlogDetailView.as_view, name='view'),
    path('edit/<int:pk>', BlogUpdateView.as_view, name='edit'),
    path('delete/<int:pk>', BlogDeleteView.as_view, name='delete'),
    path('create_version/', VersionCreateView.as_view(), name='create_version'),
    path('catalog/<int:pk>/edit', VersionUpdateView.as_view(), name='edit_version'),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

djangoProject1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from blog.views import BlogListView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('', BlogListView.as_view(), name='list'),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
# Create your models here.
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class Product(models.Model):
    id = models.AutoField(primary_key=True, verbose_name='id')
    name = models.CharField(max_length=150, verbose_name='Наименование')
    description = models.TextField(max_length=1000, verbose_name='Описание')
    image = models.ImageField(upload_to=None, height_field=None, width_field=None, max_length=100,
                              verbose_name='Изображение', **NULLABLE)
    category = models.ForeignKey("Category", on_delete=models.CASCADE)
    price = models.IntegerField(verbose_name='Цена')
    date_creation = models.CharField(max_length=150, verbose_name='Дата создания')
    date_change = models.CharField(max_length=150, verbose_name='Дата изменения')

    def __str__(self):
        return f'''
        {self.name}, {self.description},
        Категория: {self.category}
        Цена: {self.price}
        '''

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'


class Category(models.Model):
    name = models.CharField(max_length=150, verbose_name='Наименование')
    description = models.TextField(max_length=500, verbose_name='Описание')

    def __str__(self):
        return f'{self.name} {self.description}'

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Version(models.Model):
    product = models.ForeignKey("Product", on_delete=models.CASCADE, )
    # product = models.CharField(max_length=150, verbose_name='Название версии')
    version_number = models.IntegerField(verbose_name='Номер версии',)
    version_name = models.CharField(max_length=150, verbose_name='Название версии', default='base')

    def __str__(self):
        return f' {self.version_number} {self.version_name}'

    class Meta:
        verbose_name = 'Версия'
        verbose_name_plural = 'Версии'

catalog/forms.py
from django import forms

from catalog.models import Product, Version


class ProductForm(forms.ModelForm):


    class Meta:
        model = Product
        # fields = "__all__"
        fields = ('name', 'description', 'category', 'price', )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

    def clean_description(self):
        list_prohib_words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция',
                             'радар']
        cleaned_data = self.cleaned_data['description']
        for item in list_prohib_words:
            if item in cleaned_data:
                raise forms.ValidationError('Использованы недопустимые слова')
        return cleaned_data

    def clean_name(self):
        list_prohib_words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция',
                             'радар']
        cleaned_data = self.cleaned_data['name']
        for item in list_prohib_words:
            if item in cleaned_data:
                raise forms.ValidationError('Использованы недопустимые слова')
        return cleaned_data
class VersionForm(forms.ModelForm):
    class Meta:
        model = Version
        # fields = "__all__"
        fields = ('version_number', 'version_name',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

catalog/views.py
from django.forms import inlineformset_factory
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

import catalog
from catalog.forms import ProductForm, VersionForm
from catalog.models import Product, Version


# Create your views here.
def contacts(request):
    return render(request, 'catalog/contacts.html')


class ProductCreateView(CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:home')


class ProductUpdateView(UpdateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:home')

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            formset = VersionFormset(self.request.POST, instance=self.object)
        else:
            formset = VersionFormset(instance=self.object)
        context_data['formset'] = formset
        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()
        return super().form_valid(form)


class ProductListView(ListView):
    model = Product
    template_name = 'catalog/home.html'


class ProductDetailView(DetailView):
    model = Product
    template_name = 'catalog/goods.html'


class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy('catalog:home')


class VersionCreateView(CreateView):
    model = Version
    form_class = VersionForm
    success_url = reverse_lazy('catalog:home')
    # template_name = 'catalog/goods.html'


class VersionUpdateView(UpdateView):
    model = Version
    form_class = VersionForm
    success_url = reverse_lazy('catalog:home')

templates/catalog/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skystore</title>
<link href="/static/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Skystore</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="/">Каталог</a>
        <a class="p-2 btn btn-outline-primary" href="/contacts/">Контакты</a>
        <a class="p-2 btn btn-outline-primary" href={% url 'blog:list' %}>Блог</a>
    </nav>
</div>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Skystore</h1>
    <p class="lead">Skystore - онлайн магазин цифровой техники</p>
</div>

<div class="container">
    <div class="row text-center">
        {% block content%}
        {% endblock %}
    </div>

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SkyStore
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>
<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

templates/catalog/contacts.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>USA</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Redmond,WA,98052-6399</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message" placeholder="Контактный телефон" required></textarea>
                        </div>
                    </form>
                    <input type="submit">
                    <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                </div>
            </div>
        </div>
    </div>
</div>
    {% endblock %}

templates/catalog/goods.html
{% extends 'catalog/base.html' %}
{% block content %}

       <div class="card" style="width: 18rem;">
       <img src="..." class="card-img-top" alt="...">
           <div class="card-body">
               <h5 class="card-title"></h5>
                   <p class="card-text">{{object}}.</p>
               <a class="btn btn-outline-primary" href="{% url 'catalog:create_version' %}">Добавить версию</a>
    <a href="{% url 'catalog:update_product' object.pk %}" class="btn btn-primary">Изменить </a>
               <a href="{% url 'catalog:delete_product' object.pk %}" class="btn btn-primary">Удалить </a>
               <a href="#" class="btn btn-primary">Купить </a>

  </div>
</div>

{% endblock %}

templates/catalog/home.html
{% extends 'catalog/base.html' %}
{% block content %}
    <div class="col-12 mb-5">
    <a class="btn btn-outline-primary" href="{% url 'catalog:create_product' %}">Добавить продукт</a>
    </div>
        {% for object in object_list %}
       <div class="card" style="width: 18rem;">
       <img src="..." class="card-img-top" alt="...">
           <div class="card-body">
               <h5 class="card-title"></h5>
                   <p class="card-text">{{object|truncatechars:100}}.</p>
               <a href="{% url 'catalog:goods' object.pk %}">Информация о товаре </a>
               <a href="#" class="btn btn-primary">Купить </a>
  </div>
</div>
        {% endfor %}
{% endblock %}

templates/catalog/product_confirm_delete.html
{% extends 'catalog/base.html' %}
{% block content %}
    <div class = "row">
    <div class = "col-6">
        <div class = "card">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}

                    <p>Хотите удалить?"{{ object.title }}"</p>
                    <button type="submit" class="btn btn-success" >Подтвердить
                        <a href="{% url 'catalog:home' %}" class="btn btn-warning">Отмена</a>
                    </button>
                </form>
            </div>
        </div>
    </div>
    </div>
{% endblock %}

templates/catalog/product_form.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="col-10">
            <div class="card">
                <div class="card-header">
                    <h2 class="card-title">Добавление товара</h2>
                </div>
                <div class="card-body"></div>
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Сохранить</button>
                </form>
                <div class="card-footer"></div>


            </div>
        </div>
    </div>
                    </div>
    </div>
{% endblock %}

templates/catalog/version_form.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="col-10">
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                Версия
            </div>
            <div class="card-body">
            <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                {{ formset.management_form }}
                {% for form in formset.forms %}
                    {{ form.as_p }}
                {% endfor %}

                                <button type="submit" class="btn btn-success">Сохранить</button>
            </form>
                <div class="card-footer"></div>

            </div>
        </div>
    </div>
                    </div>
    </div>
{% endblock %}